owner: rcpch
repo: digital-growth-charts-upptime

sites:
  - name: growth.rcpch.ac.uk
    url: https://growth.rcpch.ac.uk
    icon: 
  - name: dev.rcpch.ac.uk
    url: https://dev.rcpch.ac.uk
  - name: api.rcpch.ac.uk (without Auth correctly returns 401)
    url: https://api.rcpch.ac.uk/v1/growth
    expectedStatusCodes:
      - 401

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime-rcpch-web-services
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RCPCH Digital Growth Charts Service Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub Actions."
  introMessage: "This page displays service status for the RCPCH Digital Growth Charts"
  navbar:
    - title: RCPCH Digital Growth Charts Service Status
      href: /
    - title: RCPCH GitHub Organisation
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
